### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by Sayali0** [prajwalsutar/MTicket#1]
Warning: mysqli_connect(): (HY000/1049): Unknown database 'train' in C:\xampp\htdocs\MTicket-main\connect.php on line 6
Error Connecting

**Comment by prajwals420** [comment]
You're getting that error because you have not added the train database in localhost/phpmyadmin
Step 1: In localhost/phpmyadmin create a new database train,
Step 2: Import train.sql file from the project folder to newly created train database in localhost/phpmyadmin
This will fix the issue.

**Comment by Sayali0** [comment]
i did that already and still they showing this, so i  guess the error is in the "connect .php" file can you check it once again plz

**Comment by prajwals420** [comment]
Usually, we get that error if we don't add the database. I just tried running the project again it's working perfectly fine. I guess you have added the password to the MySql root database. If there is any password for MySql root user you have to specify it in line 4, connect.php file. In my case there is no password that's why I have kept it blank.

**Comment by Sayali0** [comment]
it's working now 
thanks
